package aplikasikulkas;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


public class Produk extends javax.swing.JFrame {

    private PreparedStatement cmd;
    private ResultSet result;
    private boolean admin;

    public boolean isAdmin() {
        return admin;
    }

    public void setAdmin(boolean admin) {
        this.admin = admin;
    }
    
    public Produk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jFrame4 = new javax.swing.JFrame();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKulkas = new javax.swing.JTable();
        pRincian = new javax.swing.JPanel();
        pKanan = new javax.swing.JPanel();
        lblNama = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lblTipeMerk = new javax.swing.JLabel();
        lblDeskripsi = new javax.swing.JTextArea();
        lblDimensi = new javax.swing.JLabel();
        lblKapasitas = new javax.swing.JLabel();
        lblStok = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnBeli = new javax.swing.JButton();
        lblGambar = new javax.swing.JLabel();
        lblTidakDitemukan = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProduk = new javax.swing.JMenu();
        menuPesanan = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenu();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Kulkas");
        setLocation(new java.awt.Point(300, 150));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(243, 244, 246));

        jPanel5.setBackground(new java.awt.Color(243, 244, 246));

        jPanel3.setBackground(new java.awt.Color(243, 244, 246));

        tbKulkas.setFont(new java.awt.Font("Proxima Nova Rg", 0, 12)); // NOI18N
        tbKulkas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Produk", "Harga (Rp)", "Tipe", "Merk"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbKulkas.setRowHeight(24);
        tbKulkas.getTableHeader().setResizingAllowed(false);
        tbKulkas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbKulkas);

        pRincian.setBackground(new java.awt.Color(243, 244, 246));

        pKanan.setBackground(new java.awt.Color(243, 244, 246));

        lblNama.setFont(new java.awt.Font("Proxima Nova Rg", 1, 18)); // NOI18N
        lblNama.setText("Kulkas Ala Freezer (Silver)");

        lblHarga.setFont(new java.awt.Font("Proxima Nova Rg", 1, 15)); // NOI18N
        lblHarga.setText("Rp 1889000");

        lblTipeMerk.setFont(new java.awt.Font("Proxima Nova Rg", 0, 13)); // NOI18N
        lblTipeMerk.setText("Kulkas 2 Pintu | LG");

        lblDeskripsi.setBackground(new java.awt.Color(243, 244, 246));
        lblDeskripsi.setColumns(20);
        lblDeskripsi.setFont(new java.awt.Font("Proxima Nova Rg", 0, 13)); // NOI18N
        lblDeskripsi.setRows(5);
        lblDeskripsi.setWrapStyleWord(true);
        lblDeskripsi.setBorder(null);

        lblDimensi.setFont(new java.awt.Font("Proxima Nova Rg", 0, 13)); // NOI18N
        lblDimensi.setText("Dimensi 100 x 50 x 300 cm");

        lblKapasitas.setFont(new java.awt.Font("Proxima Nova Rg", 0, 13)); // NOI18N
        lblKapasitas.setText("Kapasitas 500 L");

        lblStok.setFont(new java.awt.Font("Proxima Nova Rg", 0, 13)); // NOI18N
        lblStok.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStok.setText("Stok saat ini: 12");
        lblStok.setToolTipText("");

        btnHapus.setBackground(new java.awt.Color(144, 125, 255));
        btnHapus.setFont(new java.awt.Font("Proxima Nova Rg", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(144, 125, 255));
        btnEdit.setFont(new java.awt.Font("Proxima Nova Rg", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnBeli.setBackground(new java.awt.Color(144, 125, 255));
        btnBeli.setFont(new java.awt.Font("Proxima Nova Rg", 1, 12)); // NOI18N
        btnBeli.setForeground(new java.awt.Color(255, 255, 255));
        btnBeli.setText("Beli");
        btnBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pKananLayout = new javax.swing.GroupLayout(pKanan);
        pKanan.setLayout(pKananLayout);
        pKananLayout.setHorizontalGroup(
            pKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKananLayout.createSequentialGroup()
                .addComponent(lblKapasitas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStok, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pKananLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblTipeMerk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pKananLayout.createSequentialGroup()
                .addComponent(lblDimensi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblDeskripsi)
        );
        pKananLayout.setVerticalGroup(
            pKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKananLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTipeMerk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDimensi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKapasitas)
                    .addComponent(lblStok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(pKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        lblGambar.setBackground(new java.awt.Color(255, 255, 255));
        lblGambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pRincianLayout = new javax.swing.GroupLayout(pRincian);
        pRincian.setLayout(pRincianLayout);
        pRincianLayout.setHorizontalGroup(
            pRincianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRincianLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pKanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pRincianLayout.setVerticalGroup(
            pRincianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRincianLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pRincianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pKanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        lblTidakDitemukan.setFont(new java.awt.Font("Proxima Nova Rg", 0, 13)); // NOI18N
        lblTidakDitemukan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTidakDitemukan.setText("Kulkas tidak ditemukan.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(lblTidakDitemukan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pRincian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblTidakDitemukan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pRincian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel2.setBackground(new java.awt.Color(243, 244, 246));

        lblWelcome.setFont(new java.awt.Font("Proxima Nova Rg", 1, 14)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWelcome.setText("Selamat datang, Pengguna!");

        btnTambah.setBackground(new java.awt.Color(144, 125, 255));
        btnTambah.setFont(new java.awt.Font("Proxima Nova Rg", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah +");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        txtCari.setBackground(new java.awt.Color(229, 225, 242));
        txtCari.setFont(new java.awt.Font("Proxima Nova Rg", 0, 12)); // NOI18N
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCariKeyTyped(evt);
            }
        });

        btnCari.setBackground(new java.awt.Color(144, 125, 255));
        btnCari.setFont(new java.awt.Font("Proxima Nova Rg", 1, 12)); // NOI18N
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblWelcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCari)))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(144, 125, 255));
        jMenuBar1.setBorder(null);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(240, 30));

        menuProduk.setForeground(new java.awt.Color(255, 255, 255));
        menuProduk.setText("Produk");
        menuProduk.setFont(new java.awt.Font("Proxima Nova Rg", 1, 12)); // NOI18N
        jMenuBar1.add(menuProduk);

        menuPesanan.setForeground(new java.awt.Color(255, 255, 255));
        menuPesanan.setText("Pesanan");
        menuPesanan.setFont(new java.awt.Font("Proxima Nova Rg", 1, 12)); // NOI18N
        menuPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPesananMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuPesanan);

        menuLogout.setForeground(new java.awt.Color(255, 255, 255));
        menuLogout.setText("Logout");
        menuLogout.setFont(new java.awt.Font("Proxima Nova Rg", 1, 12)); // NOI18N
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadData(String query) {
        // isi tabel
        try {
            
            DefaultTableModel tbModel = (DefaultTableModel)tbKulkas.getModel(); 
            tbModel.setRowCount(0);
            
            cmd = Main.db.getConn().prepareStatement(query);
            
            result = cmd.executeQuery();
            
            // masukkan data ke tabel
            while (result.next()) {
                String kulkas[] = {
                    result.getString("id"),
                    result.getString("nama"),
                    result.getString("harga"),
                    result.getString("tipe"),
                    result.getString("merk"),

                };
                
                tbModel.addRow(kulkas);
            }
            
            if (tbModel.getRowCount() != 0) {
                tbKulkas.addRowSelectionInterval(0, 0);
                lblTidakDitemukan.setVisible(false);
                pKanan.setVisible(true);
                lblGambar.setVisible(true);
            } else {
                lblTidakDitemukan.setVisible(true);
                pKanan.setVisible(false);
                lblGambar.setVisible(false);
            }
            
        } catch (Exception e) {
            Main.db.exceptionMsg(e);
            
        }
    }
    
    private void tbKulkas_SelectionChanged() {
        tbKulkas.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
                try {
                    cmd = Main.db.getConn().prepareStatement(
                        "SELECT * FROM kulkas " +
                        "WHERE id='" + tbKulkas.getValueAt(tbKulkas.getSelectedRow(), 0) + "'"
                    );
                    result = cmd.executeQuery();
                        
                    while (result.next()) {

                        Image gambar = Main.byteToImg(result.getBytes("gambar"));
                        //lblGambar.setSize(gambar.getWidth(rootPane), gambar.getHeight(rootPane));

                        lblGambar.setIcon(new ImageIcon(gambar));
                            
                        lblNama.setText(result.getString("nama"));
                        lblHarga.setText("Rp " + result.getString("harga"));
                        lblTipeMerk.setText(result.getString("tipe") + " | " + result.getString("merk"));
                        lblDimensi.setText(
                            "Dimensi " + result.getString("panjang") + " x " +
                                        result.getString("tinggi") + " x " +
                                        result.getString("lebar") + " cm"
                        );
                        lblKapasitas.setText("Kapasitas " + result.getString("kapasitas") + " L");
                        lblStok.setText("Stok saat ini: " + result.getString("stok"));
                        lblDeskripsi.setText(result.getString("deskripsi"));
                        lblDeskripsi.setEditable(false);
                    }
                        
                } catch (ArrayIndexOutOfBoundsException e) {
                    
                    
                } catch (Exception e) {
                    Main.db.exceptionMsg(e);
                } // end try-catch
            } // end public void
        }); // end addeventlistener
    }
    
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        new FormKulkas().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        loadData(
            "SELECT id, nama, harga, tipe, merk FROM kulkas " +
            "WHERE nama LIKE '%" + txtCari.getText() + "%'"
        );
    }//GEN-LAST:event_btnCariActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        admin = Main.username == "admin" ? true : false;

        
        lblWelcome.setText("Selamat Datang, " + Main.username + "!");
        
        // tampilan tbKulkas
        tbKulkas.getTableHeader().setBackground(new Color(144,125,255));
        tbKulkas.getTableHeader().setForeground(Color.WHITE);
        
        // invisible column id
        tbKulkas.getColumnModel().getColumn(0).setWidth(0);
        tbKulkas.getColumnModel().getColumn(0).setMinWidth(0);
        tbKulkas.getColumnModel().getColumn(0).setMaxWidth(0);
        
        // ketika pilih produk, tampilkan rincian
        tbKulkas_SelectionChanged();
        
        loadData("SELECT id, nama, harga, tipe, merk FROM kulkas");
        
        if (!admin) {
            btnBeli.setVisible(true);
            btnBeli.setLocation(btnEdit.getLocation());
            btnTambah.setVisible(false);
            btnEdit.setVisible(false);
            btnHapus.setVisible(false);
            
        } else {
            btnBeli.setVisible(false);
            btnTambah.setVisible(true);
            btnEdit.setVisible(true);
            btnHapus.setVisible(true);
        }
        
        
    }//GEN-LAST:event_formWindowOpened

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        FormKulkas kulkas = new FormKulkas();
        kulkas.setEdit(true);
        kulkas.setVisible(true);
        kulkas.setId(Integer.parseInt(tbKulkas.getValueAt(tbKulkas.getSelectedRow(), 0).toString()));
        this.dispose();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            int hapus = JOptionPane.showConfirmDialog(
                this, 
                "Apakah Anda yakin ingin menghapus produk yang dipilih?",
                "Konfirmasi",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );
            
            if (hapus == JOptionPane.OK_OPTION) {
                cmd = Main.db.getConn().prepareStatement(
                    "DELETE FROM kulkas WHERE id='" + tbKulkas.getValueAt(tbKulkas.getSelectedRow(), 0).toString() + "'"
                );
                cmd.executeUpdate();

                JOptionPane.showMessageDialog(
                    null, 
                    "Kulkas berhasil dihapus!", 
                    "Informasi", 
                    JOptionPane.INFORMATION_MESSAGE
                );

                loadData("SELECT id, nama, harga, tipe, merk FROM kulkas");
            }
           
            
        } catch (Exception e) {
            Main.db.exceptionMsg(e);
        }
        
    }//GEN-LAST:event_btnHapusActionPerformed

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
        FormPesanan pesanan = new FormPesanan();
        
        try {
            cmd = Main.db.getConn().prepareStatement(
                "SELECT * FROM kulkas " +
                "WHERE id='" + tbKulkas.getValueAt(tbKulkas.getSelectedRow(), 0).toString() + "'"
            );
            result = cmd.executeQuery();
            Kulkas kulkas = new Kulkas();

            while(result.next()) {
                kulkas.setId(result.getInt("id"));
                kulkas.setTglRilis(result.getDate("tgl_rilis"));
                kulkas.setNama(result.getString("nama"));
                kulkas.setHarga(result.getInt("harga"));
                kulkas.setMerk(result.getString("merk"));
                kulkas.setTipe(result.getString("tipe"));
                kulkas.setWarna(result.getString("warna"));
                kulkas.setDeskripsi(result.getString("deskripsi"));
                kulkas.setPanjang(result.getInt("panjang"));
                kulkas.setLebar(result.getInt("lebar"));
                kulkas.setTinggi(result.getInt("tinggi"));
                kulkas.setKapasitas(result.getInt("kapasitas"));
                kulkas.setStok(result.getInt("stok"));
                kulkas.setGambar(result.getBytes("gambar"));
            }

            pesanan.setKulkas(kulkas);
            pesanan.setVisible(true);
        } catch (Exception e) {
            Main.db.exceptionMsg(e);
        }
        
        pesanan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBeliActionPerformed

    private void menuPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPesananMouseClicked
        new RiwayatPesanan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuPesananMouseClicked

    private void txtCariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyTyped
        if (txtCari.getText().isBlank()) {
            loadData("SELECT id, nama, harga, tipe, merk FROM kulkas");
        }
    }//GEN-LAST:event_txtCariKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeli;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lblDeskripsi;
    private javax.swing.JLabel lblDimensi;
    private javax.swing.JLabel lblGambar;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblKapasitas;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblStok;
    private javax.swing.JLabel lblTidakDitemukan;
    private javax.swing.JLabel lblTipeMerk;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuPesanan;
    private javax.swing.JMenu menuProduk;
    private javax.swing.JPanel pKanan;
    private javax.swing.JPanel pRincian;
    private javax.swing.JTable tbKulkas;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
