/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasikulkas;

import java.awt.Color;
import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aziizah Oki Shofrina
 */
public class RiwayatPesanan extends javax.swing.JFrame {

    private PreparedStatement cmd;
    private ResultSet result;
    
    public RiwayatPesanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPesanan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProduk = new javax.swing.JMenu();
        menuPesanan = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Kulkas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(243, 244, 246));

        tbPesanan.setFont(new java.awt.Font("Proxima Nova Rg", 0, 12)); // NOI18N
        tbPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tanggal", "Pembelian", "Pembayaran (Rp)", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPesanan.setRowHeight(24);
        tbPesanan.getTableHeader().setResizingAllowed(false);
        tbPesanan.getTableHeader().setReorderingAllowed(false);
        tbPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPesanan);

        jPanel2.setBackground(new java.awt.Color(144, 125, 255));

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Proxima Nova Rg", 1, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Riwayat Pesanan Anda");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(144, 125, 255));
        jMenuBar1.setBorder(null);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(240, 30));

        menuProduk.setForeground(new java.awt.Color(255, 255, 255));
        menuProduk.setText("Produk");
        menuProduk.setFont(new java.awt.Font("Proxima Nova Rg", 1, 12)); // NOI18N
        menuProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProdukMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuProduk);

        menuPesanan.setForeground(new java.awt.Color(255, 255, 255));
        menuPesanan.setText("Pesanan");
        menuPesanan.setFont(new java.awt.Font("Proxima Nova Rg", 1, 12)); // NOI18N
        jMenuBar1.add(menuPesanan);

        menuLogout.setForeground(new java.awt.Color(255, 255, 255));
        menuLogout.setText("Logout");
        menuLogout.setFont(new java.awt.Font("Proxima Nova Rg", 1, 12)); // NOI18N
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadData() {
        try {
            
            DefaultTableModel tbModel = (DefaultTableModel)tbPesanan.getModel(); 
            tbModel.setRowCount(0);
            
            cmd = Main.db.getConn().prepareStatement(
                "SELECT p.id, p.tgl_pesanan, p.jumlah, p.total_pembayaran, p.status, p.id_kulkas, k.nama FROM pesanan p " +
                "INNER JOIN kulkas k " +
                "ON (p.id_kulkas = k.id) " +
                (Main.username == "admin" ? "" : "WHERE username='"+Main.username+"'")
            );
            
            result = cmd.executeQuery();
            
            // masukkan data ke tabel
            while (result.next()) {
                String pesanan[] = {
                    result.getString("id"),
                    result.getString("tgl_pesanan"),
                    result.getString("nama") + " x " + result.getString("jumlah"),
                    result.getString("total_pembayaran"),
                    result.getString("status"),
                };
                
                tbModel.addRow(pesanan);
            }
            
            tbPesanan.addRowSelectionInterval(0, 0);
            
        } catch (Exception e) {
            Main.db.exceptionMsg(e);
            
        }
    }
    
private void tbPesanan_SelectionChanged() {
        tbPesanan.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
                
               
            } // end public void
        }); // end addeventlistener
    }
    
    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void menuProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProdukMouseClicked
        new Produk().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuProdukMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
                // tampilan tbKulkas
        tbPesanan.getTableHeader().setBackground(new Color(144,125,255));
        tbPesanan.getTableHeader().setForeground(Color.WHITE);
        loadData();
        tbPesanan_SelectionChanged();
    }//GEN-LAST:event_formWindowOpened

    private void tbPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPesananMouseClicked
        int row = tbPesanan.rowAtPoint(evt.getPoint());
        int col = tbPesanan.columnAtPoint(evt.getPoint());
        
        if (!(row >= 0 && col >= 0)) {
            return;
        } 

        try {
            cmd = Main.db.getConn().prepareStatement(
                    "SELECT * FROM pesanan " +
                            "WHERE id='" + tbPesanan.getValueAt(tbPesanan.getSelectedRow(), 0) + "'");
            result = cmd.executeQuery();

            Pesanan pesanan = new Pesanan();
            int idKulkas = 0;

            while (result.next()) {
                pesanan.setId(result.getString("id"));
                pesanan.setTglPesanan(result.getDate("tgl_pesanan"));
                pesanan.setJumlah(result.getInt("jumlah"));
                pesanan.setTotalPembayaran(result.getInt("total_pembayaran"));
                pesanan.setNamaPenerima(result.getString("nama_penerima"));
                pesanan.setAlamat(result.getString("alamat"));
                pesanan.setStatus(result.getString("status"));
                // pesanan.setIdKulkas(kulkas);
                Customer pemesan = new Customer();
                pemesan.setUsername(result.getString("username"));
                pesanan.setUsername(pemesan);
                

                idKulkas = result.getInt("id_kulkas");

            }

            cmd = Main.db.getConn().prepareStatement(
                    "SELECT * FROM kulkas " +
                            "WHERE id='" + Integer.toString(idKulkas) + "'");
            result = cmd.executeQuery();

            Kulkas kulkas = new Kulkas();
            while (result.next()) {
                kulkas.setId(result.getInt("id"));
                kulkas.setTglRilis(result.getDate("tgl_rilis"));
                kulkas.setNama(result.getString("nama"));
                kulkas.setHarga(result.getInt("harga"));
                kulkas.setMerk(result.getString("merk"));
                kulkas.setTipe(result.getString("tipe"));
                kulkas.setWarna(result.getString("warna"));
                kulkas.setDeskripsi(result.getString("deskripsi"));
                kulkas.setPanjang(result.getInt("panjang"));
                kulkas.setLebar(result.getInt("lebar"));
                kulkas.setTinggi(result.getInt("tinggi"));
                kulkas.setKapasitas(result.getInt("kapasitas"));
                kulkas.setStok(result.getInt("stok"));
                kulkas.setGambar(result.getBytes("gambar"));
            }
            pesanan.setIdKulkas(kulkas);

            FormPesanan struk = new FormPesanan();
            struk.setKulkas(kulkas);
            struk.setPesanan(pesanan);
            struk.setVisible(true);

        } catch (ArrayIndexOutOfBoundsException e) {

        } catch (Exception e) {
            Main.db.exceptionMsg(e);
        } // end try-catch

    }//GEN-LAST:event_tbPesananMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiwayatPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiwayatPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiwayatPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiwayatPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiwayatPesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuPesanan;
    private javax.swing.JMenu menuProduk;
    private javax.swing.JTable tbPesanan;
    // End of variables declaration//GEN-END:variables
}
